// <auto-generated />
namespace RentApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IdevikaopoljazareferencekodAppUseraiRente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdevikaopoljazareferencekodAppUseraiRente));
        
        string IMigrationMetadata.Id
        {
            get { return "201806150657492_Id-evi kao polja za reference kod AppUser-a i Rent-e"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
